#!/usr/bin/env php
<?php
$path 	= '/Users/cccaldas/Projects/as3-interpreter';
$file 	= file_get_contents($argv[1]);
$file 	= str_replace("#!/usr/bin/env as3", "", $file);
$tmp 	= $path.'/tmp/tmp.as';

file_put_contents($tmp, $file);
echo shell_exec("$path/lib/redshell $tmp");
?>